# Generated by Django 3.1.6 on 2021-02-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
